### ISSUE TITLE
Pull from master

### ISSUE THREAD

**Issue by Atinux** [translation-gang/ru.docs.nuxtjs#16]
Hi there,

Can you pull from master, we added the translation for the "Version" and "Search".

See https://github.com/nuxt/docs/blob/master/ru/lang.json#L21

Thank you :)

**Comment by gbezyuk** [comment]
@Atinux thank you for noticing. It's done by @Alex-Sokolov with #17.

**Comment by Atinux** [comment]
Great!

I tried to translate Search in Russian with Google Translate but it was apparently not the right word 😆

**Comment by gbezyuk** [comment]
@Atinux yeah, Russian is sorta weird =)
