### ISSUE TITLE
typo in guide/assets.md

### ISSUE THREAD

**Issue by akimov-anton** [translation-gang/ru.docs.nuxtjs#54]
Опечатка в https://ru.nuxtjs.org/guide/assets
**Подоный** подход уменьшает количество HTTP-запросов ->
Подо**б**ный подход уменьшает количество HTTP-запросов

Такая конфигурация означает, что каждый файл с размером, меньшим 1 **KO** ->
Такая конфигурация означает, что каждый файл с размером, меньшим 1 K**B**

И там еще встречаются KO

**Comment by Alex-Sokolov** [comment]
Может сделаете PR? Даже с сайте GitHub можно файлы подредактировать и сразу PR создать

**Comment by akimov-anton** [comment]
> Может сделаете PR? Даже с сайте GitHub можно файлы подредактировать и сразу PR создать

Не пойму почему там текст на английском.. В русской версии. Как выйти на русский? Подскажите, пожалуйста :)

**Comment by Alex-Sokolov** [comment]
https://github.com/translation-gang/ru.docs.nuxtjs/blob/translation-ru/ru/guide/assets.md

Обновляли документацию, местами было много правок что от русской версии мало чего осталось :) переносить рук не хватает
